### ISSUE TITLE
in create_seqlogo_dataframe     seqlen = len(sequences[0]) IndexError: list index out of range

### ISSUE THREAD

**Issue by kavonrtep** [mccannj9/ace-kit#17]
python start.py -a /mnt/raid/users/tmp/rypos/seqclust/clustering/clusters/dir_CL0014/contigs.ace -o tmp`

CL14Contig48
CL14Contig79
CL14Contig173
CL14Contig334
CL14Contig432
Traceback (most recent call last):
  File "start.py", line 52, in <module>
    results_dict, all_reads = finder.fit()
  File "/mnt/raid/users/petr/workspace/ace-kit/kit/finder.py", line 33, in fit
    self.generate_output_for_boundaries(cands, derivs)
  File "/mnt/raid/users/petr/workspace/ace-kit/kit/finder.py", line 48, in generate_output_for_boundaries
    boundary.set_logo(save=logo_out)
  File "/mnt/raid/users/petr/workspace/ace-kit/kit/contig.py", line 315, in set_logo
    df = create_seqlogo_dataframe(seqs)
  File "/mnt/raid/users/petr/workspace/ace-kit/kit/utils.py", line 58, in create_seqlogo_dataframe
    seqlen = len(sequences[0])
IndexError: list index out of range

I had to add txt suffix to ace file to be able to upload it to github:

[contigs.ace.txt](https://github.com/mccannj9/ace-kit/files/4923743/contigs.ace.txt)

**Comment by mccannj9** [comment]
Sorry, I didn't see this before. I think this function has been changed since I stopped using the start.py script. I should probably remove this script from the directory.
